spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 841f992e11bf10fc0c8f
            client-secret: 42df44448fdc470f7864d785eba5eacc60320cc0

example:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

